{
 "title": "Ship Details",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "Ship",
    "query": {
     "query": "label_values(spacetradership_trade_cycles, ship_id)"
    }
   },
   {
    "name": "Good",
    "query": {
     "query": "label_values(spacetradership_goods_sold, good)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Operational",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "up{}" }
   ]
  },
  {
   "title": "Cycles",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "spacetradership_trade_cycles{ship_id=~\"$Ship\"}"
    }
   ]
  },
  {
   "title": "Fuel Consumed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "spacetradership_fuel_consumed{ship_id=~\"$Ship\"}",
     "legendFormat": "{{ship_id}}"
    }
   ]
  },
  {
   "title": "Goods Bought",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(spacetradership_goods_bought{good=~\"$Good\",ship_id=~\"$Ship\"}[$__rate_interval])",
     "legendFormat": "{{good}}"
    }
   ]
  },
  {
   "title": "Goods sold",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(spacetradership_goods_sold{good=~\"$Good\",ship_id=~\"$Ship\"}[10m])",
     "legendFormat": "{{good}}"
    }
   ]
  },
  {
   "title": "Money Earned By Goods",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "rate(spacetradership_money_earned{good=~\"$Good\",ship_id=~\"$Ship\"}[$__rate_interval])",
     "legendFormat": "{{good}}"
    }
   ]
  },
  {
   "title": "Money Spent By Goods",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "rate(spacetradership_money_spent{good=~\"$Good\",ship_id=~\"$Ship\"}[$__rate_interval])",
     "legendFormat": "{{good}}"
    }
   ]
  }
 ]
}